* literate-clojure-mode

Set of utilities to complement a clojure literate programming workflow using org-mode.

** Installation

In spacemacs, follow these steps to install literate-clojure-mode:

1. =git clone git@github.com:RakutenReady/literate-clojure-mode.git ~/.emacs.d/private/local/literate-clojure-mode=
2. Add =(literate-clojure-mode :location local)= to =dotspacemacs-additional-packages=

You can now enable =literate-clojure-mode=.

** Configuration
*** Enable =literate-clojure-mode=

To enable =literate-clojure-mode=, add this to your user configuration.

#+BEGIN_SRC emacs-lisp
(require 'literate-clojure-mode)
(literate-clojure-mode t)
#+END_SRC

This will add hooks to org-mode and clojure files to enables their respective minor modes.

*** Add Keybindings

You can add keybindings to easily invoke interactive functions provided in the package:

#+BEGIN_SRC emacs-lisp
(spacemacs/set-leader-keys "o o" 'litclj-tangle-goto-org)
(spacemacs/set-leader-keys "o t" 'litclj-goto-tangle)
(spacemacs/set-leader-keys "o d" 'litclj-detangle-all)
(spacemacs/set-leader-keys "o u" 'litclj-add-tangle-test-path)
#+END_SRC

In spacemacs, these functions can also be invoked via =SPC SPC=.

*** Feature flags

It is possible to turn on and off specific features of =literate-clojure-mode= by setting variables.

| Variable                           | Description                                                                                                                  |
|------------------------------------+------------------------------------------------------------------------------------------------------------------------------|
| =litclj-enable-follow-mode=        | "Enables the auto-follow mode which shows the relevant section of the org mode file relative to the current clj block code." |
| =litclj-enable-auto-detangle-mode= | "Enables the auto-detangle mode which detangles the current clj buffer after modifications."                                 |
| =litclj-enable-validate-mode=      | "Enables validation of org-mode files on save and load to ensure the noweb block ids are unique."                            |
